name: kopo
description: Kopo package can search for Korean postal addresses using the following postal code search services. If necessary, you can use the English address by clicking the View English button.
version: 0.1.3
author: Paul Han <paul@salondecode.io>
homepage: https://github.com/salondecode/kopo

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
